-- INSERT INTO club (
--     club_id,
--     nom,
--     adress,
--     date_de_creation,
--     telephone,
--     faxe,
--     couleur_principale,
--     couleur_réserve
--   )
-- VALUES 
--   (
--     'JSOMA',
--     'J.S.O Maamria',
--     'rut principal stade communal heuraoua arbi abdelouahab',
--     '2006-1-1',
--     023958098,
--     023958098,
--     'Vert',
--     'Rouge'
--   );


-- INSERT INTO joueur (
--     personne_id,
--     nom,
--     prenom,
--     date_de_naissance,
--     lieu_de_naissance,
--     nationalite
--   )
-- VALUES (
--     '1',
--     'BERROUSSI',
--     'Imad',
--     '2000-6-18',
--     'el harrache, Alger',
--     'Algerien'
--   ),
--   (
--     '2',
--     'LEBCIR',
--     'Abderazzak',
--     '1988-7-5',
--     'BOUSSAADA, Msila',
--     'Algerien'
--   ),
--   (
--     '3',
--     'BAHMED',
--     'Toufik',
--     '1996-10-20',
--     'H-DEY, Alger',
--     'Algerien'
--   ),
--   (
--     '4',
--     'TAGAOUNAMANE',
--     'Billal',
--     '1991-7-17',
--     'REGHAIA, Alger',
--     'Algerien'
--   ),
--   (
--     '5',
--     'ATTIG',
--     'Ahmed Aymen Eddine',
--     '1995-7-3',
--     'heuraoua, Alger',
--     'Algerien'
--   ),
--   (
--     '6',
--     'AROUS',
--     'Rafik',
--     '1995-5-28',
--     'AIN TAYA, Alger',
--     'Algerien'
--   ),
--   (
--     '7',
--     'BENDECHACHE',
--     'Mohamed Lamine',
--     '1992-3-19',
--     'rouiba, Alger',
--     'Algerien'
--   ),
--   (
--     '8',
--     'BEHAR',
--     'Mokhtar',
--     '2000-2-13',
--     'rouiba, Alger',
--     'Algerien'
--   ),
--   (
--     '9',
--     'DJEMMAH',
--     'Oussama',
--     '1995-6-19',
--     'rouiba, Alger',
--     'Algerien'
--   ),
--   (
--     '10',
--     'FEZZA',
--     'Chouaib',
--     '2001-2-6',
--     'beni messous, Alger',
--     'Algerien'
--   ),
--   (
--     '11',
--     'BOUAFIA',
--     'Ahmed Alamine',
--     '1999-5-28',
--     'reghaia, Alger',
--     'Algerien'
--   );
